openapi: 3.0.1
info:
  title: Compass-Lisa
  description: CompassLisa um seguimento de negócio de carros de luxo e semi luxo para alugar.
  version: 0.0.1
  license:
    name: "Lincença: MIT"
    url: https://opensource.org/licenses/MIT
externalDocs:
  description: Repositório-(Github)
  url: https://github.com/EdsoonJr/CompassLisa-API
servers:
- url: http://localhost:3000/api/v1/
  description: API Compass-Lisa
paths:
  /car:
    get:
      summary: Listar Todos os Veículos
      parameters:
      - name: modelo
        in: query
        schema:
          type: string
        required: false
      - name: cor
        in: query
        schema:
          type: string
        required: false
      - name: ano
        in: query
        schema:
          type: string
        required: false
      - name: acessorios
        in: query
        schema:
          type: string
        required: false
      - name: quantidadePassageiros
        in: query
        schema:
          type: string
        required: false
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                    modelo:
                       type: string
                    cor: 
                       type: string
                    ano: 
                       type: string
                    acessorios:
                       type: string
                    quantidadePassageiros: 
                       type: string
    post: 
      summary: Cadastrar Veículo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                modelo:
                  type: string
                cor:
                  type: string
                ano:
                  type: string
                acessorios:
                  type: string
                quantidadePassageiros:
                  type: string
      responses: 
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties: 
                  modelo:
                    type: string
                  cor: 
                    type: string
                  ano: 
                    type: string
                  acessorios:
                    type: string
                  quantidadePassageiros: 
                    type: string
        400:
          description: Cadastro falhou
          content:
            application/json: 
              example: "Veículo not registered"
  /car/{_id}:
    get:
      summary: Atualiza um Veículo
      parameters:
      - name: _id
        in: path
        schema:
          type: string
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                    modelo:
                       type: string
                    cor: 
                       type: string
                    ano: 
                       type: string
                    acessorios:
                       type: string
                    quantidadePassageiros: 
                       type: string       
    put:
      summary: Atualiza um Veículo
      parameters:
      - name: _id
        in: path
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                modelo:
                   type: string
                cor: 
                  type: string
                ano: 
                   type: string
                acessorios:
                  type: string
                quantidadePassageiros: 
                    type: string
               
      responses:
        200:
          description: Veículo Atualizado
          content:
            application/json:
              schema:
                type: object
                properties:
                 modelo:
                  type: string
                 cor: 
                   type: string
                 ano: 
                  type: string
                 acessorios:
                  type: string
                 quantidadePassageiros: 
                    type: string
        400:
          description: Erro ao atualizar funcionário
          content:
            application/json:
              example: "bad request"
    delete:
      summary: Excluir Veículo
      parameters:
      - name: _id
        in: path
        schema:
          type: string
        required: true
      responses: 
        204:
          description: Veículo Excluído
          content:
            application/json:
              example: "Deleted Veichle"
        404:
          description: Erro ao Excluir Veículo
          content:
            application/json:
              example: "Veículo não Encontrado"
  /people:
    post:
      summary: Cadastrar Pessoa
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              properties:
                _id:
                  type: string
                nome:
                  type: string
                cpf: 
                  type: string
                data_nascimento: 
                  type: string
                email:
                  type: string
                senha:
                  type: string
                habilitado:
                  type: string

      responses: 
        201:
          description: produto cadastrado
          content:
             application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nome:
                    type: string
                  cpf: 
                    type: string
                  data_nascimento: 
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  habilitado:
                    type: string
                  
        400:   
          description: produto cadastrado
          content: 
            application/json:
                   example: "Bad request"
    get:
      summary: Listar Todos as Pessoas
      parameters:
      - in: query
        name: nome
        schema:
          type: string
      - in: query
        name: cpf
        schema:
          type: integer
      - in: query
        name: data_nascimento
        schema:
          type: string
      - in: query
        name: email
        schema:
          type: string
      - in: query
        name: senha
        schema:
          type: string
      - in: query
        name: habilitado
        schema:
          type: string
 
 
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nome:
                    type: string
                  cpf: 
                    type: string
                  data_nascimento: 
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  habilitado:
                    type: string
  /people/{_id}:
    get:
      summary: Buscar Pessoa Por Id
      parameters:
      - name: _id
        in: path
        schema:
          type: string
        required: true
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nome:
                    type: string
                  cpf: 
                    type: string
                  data_nascimento: 
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  habilitado:
                    type: string

    put:
      summary: Atualizar uma Pessoa
      parameters:
      - name: _id
        in: path
        schema:
          type: string
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                  _id:
                    type: string
                  nome:
                    type: string
                  cpf: 
                    type: string
                  data_nascimento: 
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  habilitado:
                    type: string
               
      responses:
        200:
          description: Pessoa Atualizada
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nome:
                    type: string
                  cpf: 
                    type: string
                  data_nascimento: 
                    type: string
                  email:
                    type: string
                  senha:
                    type: string
                  habilitado:
                    type: string
        400:
          description: Erro ao atualizar Pessoa
          content:
            application/json:
              example: "bad request"
    delete:
      summary: Excluir Pessoa
      parameters:
      - name: _id
        in: path
        schema:
          type: string
        required: true
      responses: 
        204:
          description: Pessoa Excluída
          content:
            application/json:
              example: "Deleted People"
        404:
          description: Erro ao Excluir Pessoa
          content:
            application/json:
              example: "Pessoa não Encontrada"